# Generated by graft scaffold

override {
}
module "network" {
  override {
    # resource "azurerm_virtual_network" "vnet" {}

    # resource "azurerm_subnet" "subnet_count" {}

    # resource "azurerm_subnet" "subnet_for_each" {}

  }
}
