# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.example
  resource "azurerm_resource_group" "example" {
    tags = {
      Creator     = "admin@contoso.com"
      DateCreated = "2026-01-15T09:22:31Z"
      environment = "production"
      owner       = "platform-team"
      project     = "graft"
    }
  }

}
module "network" {
  override {
    # Absorb drift for: module.network.azurerm_virtual_network.vnet
    resource "azurerm_virtual_network" "vnet" {
      tags = {
        environment = "production"
        managed_by  = "terraform"
        owner       = "platform-team"
      }
    }

    # Absorb drift for: module.network.azurerm_subnet.subnet_for_each["web-subnet"]
    resource "azurerm_subnet" "subnet_for_each" {
      default_outbound_access_enabled = lookup({
        web-subnet = false
      }, each.key, graft.source)
      service_endpoints = lookup({
        web-subnet = ["Microsoft.Web"]
      }, each.key, graft.source)
    }

  }
}

