# Tests that graft absorb handles for_each-indexed resource drift by generating
# lookup() expressions with each.key as the selector and graft.source fallback.

command      = "absorb"
command_args = ["-p", "providers.json", "plan.json"]

expected "absorb.graft.hcl" {
  content {
# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.main["web"], azurerm_resource_group.main["api"]
  resource "azurerm_resource_group" "main" {
    tags = lookup({
      "api" = {
        environment = "staging"
        owner       = "apiteam"
        project     = "graft"
      }
      "web" = {
        environment = "production"
        owner       = "webteam"
        project     = "graft"
      }
    }, each.key, graft.source)
  }

}
  }
}
