# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.env[0], azurerm_resource_group.env[1]
  resource "azurerm_resource_group" "env" {
    tags = lookup({
      0 = {
        environment = "production"
        owner       = "drifttest"
        project     = "graft"
      }
      1 = {
        environment = "staging"
        owner       = "drifttest"
        project     = "graft"
      }
    }, count.index, graft.source)
  }

  # Absorb drift for: azurerm_resource_group.team["api"], azurerm_resource_group.team["web"]
  resource "azurerm_resource_group" "team" {
    location = lookup({
      "api" = "westus"
      "web" = "centralus"
    }, each.key, graft.source)
  }

}
