# Tests that graft scaffold generates a manifest for discovered modules.

command = "scaffold"

expected "scaffold.graft.hcl" {
  content {
    # Generated by graft scaffold

    override {
    }
    module "app" {
      override {
        # resource "local_file" "config" {}

        # resource "local_file" "data" {}

      }
    }
  }
}
