# Tests that graft absorb handles count-indexed resource drift by generating
# lookup() expressions with count.index as the selector and graft.source fallback.

command      = "absorb"
command_args = ["-p", "providers.json", "plan.json"]

expected "absorb.graft.hcl" {
  content {
# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.main[0], azurerm_resource_group.main[1]
  resource "azurerm_resource_group" "main" {
    tags = lookup({
      0 = {
        environment = "production"
        owner       = "drifttest"
        project     = "graft"
      }
      1 = {
        environment = "staging"
        owner       = "drifttest"
        project     = "graft"
      }
    }, count.index, graft.source)
  }

}
  }
}
