# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.test
  resource "azurerm_resource_group" "test" {
    tags = {
      Creator     = "user@example.com"
      DateCreated = "2026-02-06T13:39:05Z"
      environment = "production"
      owner       = "drifttest"
      project     = "graft"
    }
  }

}
