# Tests that graft absorb handles count-indexed resources with block-type drift.
# Two NSG instances [0] and [1] each have different security_rule drift.
# The manifest should generate:
#   - lookup() for tags with count.index selector and graft.source fallback
#   - dynamic "security_rule" block with lookup() per index and [] fallback
#   - _graft { remove = ["security_rule"] } to replace original static blocks

command      = "absorb"
command_args = ["-p", "providers.json", "plan.json"]

expected "absorb.graft.hcl" {
  content {
# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_network_security_group.nsg[0], azurerm_network_security_group.nsg[1]
  resource "azurerm_network_security_group" "nsg" {
    tags = lookup({
      "0" = {
        environment = "production"
        project     = "graft"
      }
      "1" = {
        environment = "staging"
        project     = "graft"
      }
    }, count.index, graft.source)
    dynamic "security_rule" {
      for_each = lookup({
        "0" = [{
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "22"
          direction                  = "Inbound"
          name                       = "allow-ssh"
          priority                   = 100
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "443"
          direction                  = "Inbound"
          name                       = "allow-https"
          priority                   = 200
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
        }]
        "1" = [{
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "80"
          direction                  = "Inbound"
          name                       = "allow-http"
          priority                   = 100
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "443"
          direction                  = "Inbound"
          name                       = "allow-https"
          priority                   = 200
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Deny"
          destination_address_prefix = "*"
          destination_port_range     = "*"
          direction                  = "Inbound"
          name                       = "deny-all"
          priority                   = 4096
          protocol                   = "*"
          source_address_prefix      = "*"
          source_port_range          = "*"
        }]
      }, count.index, [])
      content {
        access                     = security_rule.value.access
        destination_address_prefix = security_rule.value.destination_address_prefix
        destination_port_range     = security_rule.value.destination_port_range
        direction                  = security_rule.value.direction
        name                       = security_rule.value.name
        priority                   = security_rule.value.priority
        protocol                   = security_rule.value.protocol
        source_address_prefix      = security_rule.value.source_address_prefix
        source_port_range          = security_rule.value.source_port_range
      }
    }
    _graft {
      remove = ["security_rule"]
    }
  }

}
  }
}
