# Tests that graft absorb detects tag drift on an Azure resource group.
# Created from a real Azure deployment where tags were changed via az CLI:
#   az group update --name graft-absorb-test-rg --tags environment=production project=graft owner=drifttest
# Azure policy also added Creator and DateCreated tags automatically.

command      = "absorb"
command_args = ["-p", "providers.json", "plan.json"]

expected "absorb.graft.hcl" {
  content {
# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.test
  resource "azurerm_resource_group" "test" {
    tags = {
      Creator     = "user@example.com"
      DateCreated = "2026-02-06T13:39:05Z"
      environment = "production"
      owner       = "drifttest"
      project     = "graft"
    }
  }

}
  }
}
