# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_linux_virtual_machine.vm["web"], azurerm_linux_virtual_machine.vm["api"]
  resource "azurerm_linux_virtual_machine" "vm" {
    dynamic "os_disk" {
      for_each = lookup({
        "api" = [{
          caching              = "ReadOnly"
          disk_size_gb         = 64
          storage_account_type = "StandardSSD_LRS"
        }]
        "web" = [{
          caching              = "ReadWrite"
          disk_size_gb         = 50
          storage_account_type = "Premium_LRS"
        }]
      }, each.key, [])
      content {
        caching              = os_disk.value.caching
        disk_size_gb         = os_disk.value.disk_size_gb
        storage_account_type = os_disk.value.storage_account_type
      }
    }
    _graft {
      remove = ["os_disk"]
    }
  }

  # Absorb drift for: azurerm_network_security_group.nsg[0], azurerm_network_security_group.nsg[1]
  resource "azurerm_network_security_group" "nsg" {
    tags = lookup({
      0 = {
        environment = "production"
        project     = "graft"
      }
      1 = {
        environment = "staging"
        project     = "graft"
      }
    }, count.index, graft.source)
    dynamic "security_rule" {
      for_each = lookup({
        0 = [{
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "22"
          direction                  = "Inbound"
          name                       = "allow-ssh"
          priority                   = 100
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "443"
          direction                  = "Inbound"
          name                       = "allow-https"
          priority                   = 200
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
        }]
        1 = [{
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "80"
          direction                  = "Inbound"
          name                       = "allow-http"
          priority                   = 100
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "443"
          direction                  = "Inbound"
          name                       = "allow-https"
          priority                   = 200
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
          }, {
          access                     = "Deny"
          destination_address_prefix = "*"
          destination_port_range     = "*"
          direction                  = "Inbound"
          name                       = "deny-all"
          priority                   = 4096
          protocol                   = "*"
          source_address_prefix      = "*"
          source_port_range          = "*"
        }]
      }, count.index, [])
      content {
        access                     = security_rule.value.access
        destination_address_prefix = security_rule.value.destination_address_prefix
        destination_port_range     = security_rule.value.destination_port_range
        direction                  = security_rule.value.direction
        name                       = security_rule.value.name
        priority                   = security_rule.value.priority
        protocol                   = security_rule.value.protocol
        source_address_prefix      = security_rule.value.source_address_prefix
        source_port_range          = security_rule.value.source_port_range
      }
    }
    _graft {
      remove = ["security_rule"]
    }
  }

}
