# Tests that graft scaffold can target a specific module using command_args.

command      = "scaffold"
command_args = ["infra.nested"]

expected "scaffold.graft.hcl" {
  content {
    # Generated by graft scaffold

    module "infra" {
      module "nested" {
        override {
          # resource "local_file" "nested_config" {}

        }
      }

    }
  }
  # infra module's resources should not be scaffolded since we only target infra.nested
  not_contains = ["infra_config"]
}
