package absorb

import (
	"fmt"
	"sort"

	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	tfjson "github.com/hashicorp/terraform-json"
)

type ModuleItem struct {
	Name     string
	Children map[string]*ModuleItem
	Changes  []DriftChange
}

func NewModuleItem(name string) *ModuleItem {
	return &ModuleItem{
		Name:     name,
		Children: make(map[string]*ModuleItem),
		Changes:  []DriftChange{},
	}
}

func (m *ModuleItem) AddChange(change DriftChange) *ModuleItem {
	current := m
	for _, modName := range change.ModulePath {
		if _, exists := current.Children[modName]; !exists {
			current.Children[modName] = NewModuleItem(modName)
		}
		current = current.Children[modName]
	}
	current.Changes = append(current.Changes, change)
	return current
}

func (m *ModuleItem) IsRoot() bool {
	return m.Name == ""
}

func (m *ModuleItem) ToHCL(providerSchemas *tfjson.ProviderSchemas) hclwrite.Tokens {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	if m.IsRoot() {
		rootBody.AppendUnstructuredTokens(hclwrite.Tokens{
			{Type: hclsyntax.TokenComment, Bytes: []byte("# Generated by graft absorb\n")},
			{Type: hclsyntax.TokenComment, Bytes: []byte("# This manifest contains overrides to match the current remote state\n")},
		})
		rootBody.AppendNewline()
	}

	if len(m.Changes) > 0 {
		overrideBlock := rootBody.AppendNewBlock("override", nil)
		overrideBody := overrideBlock.Body()

		sort.Slice(m.Changes, func(i, j int) bool {
			if m.Changes[i].ResourceType != m.Changes[j].ResourceType {
				return m.Changes[i].ResourceType < m.Changes[j].ResourceType
			}
			return m.Changes[i].ResourceName < m.Changes[j].ResourceName
		})

		for _, change := range m.Changes {
			schema := lookupResourceSchema(providerSchemas, change.ProviderName, change.ResourceType)
			block := change.ToBlock(schema)
			if block == nil {
				continue
			}
			overrideBody.AppendUnstructuredTokens(hclwrite.Tokens{
				{Type: hclsyntax.TokenComment, Bytes: []byte(fmt.Sprintf("# Absorb drift for: %s\n", change.Address))},
			})
			overrideBody.AppendBlock(block)
			overrideBody.AppendNewline()
		}
	}

	if len(m.Children) > 0 {
		var childNames []string
		for name := range m.Children {
			childNames = append(childNames, name)
		}
		sort.Strings(childNames)

		for _, childName := range childNames {
			child := m.Children[childName]
			modBlock := rootBody.AppendNewBlock("module", []string{child.Name})
			modBody := modBlock.Body()
			childTokens := child.ToHCL(providerSchemas)
			modBody.AppendUnstructuredTokens(childTokens)
			rootBody.AppendNewline()
		}
	}

	return f.BuildTokens(nil)
}
