# Generated by graft absorb
# This manifest contains overrides to match the current remote state

override {
  # Absorb drift for: azurerm_resource_group.test
  resource "azurerm_resource_group" "test" {
    tags = {
      Creator     = "user@example.com"
      DateCreated = "2026-02-06T14:50:54Z"
      environment = "production"
      owner       = "drifttest"
      project     = "graft"
      team        = "platform"
    }
  }

}
module "network" {
  override {
    # Absorb drift for: module.network.azurerm_virtual_network.main
    resource "azurerm_virtual_network" "main" {
      subnet {
        address_prefixes                              = ["10.0.1.0/24"]
        default_outbound_access_enabled               = false
        name                                          = "web-subnet"
        private_endpoint_network_policies             = "Disabled"
        private_link_service_network_policies_enabled = true
      }
      subnet {
        address_prefixes                              = ["10.0.2.0/24"]
        default_outbound_access_enabled               = false
        name                                          = "app-subnet"
        private_endpoint_network_policies             = "Disabled"
        private_link_service_network_policies_enabled = true
      }
      subnet {
        address_prefixes                              = ["10.0.3.0/24"]
        default_outbound_access_enabled               = false
        name                                          = "db-subnet"
        private_endpoint_network_policies             = "Disabled"
        private_link_service_network_policies_enabled = true
      }
      tags = {
        environment = "production"
        layer       = "network"
        owner       = "drifttest"
      }
      _graft {
        remove = ["subnet"]
      }
    }

  }
  module "security" {
    override {
      # Absorb drift for: module.network.module.security.azurerm_network_security_group.main
      resource "azurerm_network_security_group" "main" {
        security_rule {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "22"
          direction                  = "Inbound"
          name                       = "allow-ssh"
          priority                   = 100
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
        }
        security_rule {
          access                     = "Allow"
          destination_address_prefix = "*"
          destination_port_range     = "443"
          direction                  = "Inbound"
          name                       = "allow-https"
          priority                   = 200
          protocol                   = "Tcp"
          source_address_prefix      = "10.0.0.0/8"
          source_port_range          = "*"
        }
        tags = {
          compliance  = "required"
          environment = "production"
          layer       = "security"
          owner       = "drifttest"
        }
        _graft {
          remove = ["security_rule"]
        }
      }

    }
  }

}
